/*
 * This source file was generated by the Gradle 'init' task
 */
package tiny.blockchain;
import java.util.*;



public class App {
    public static void main(String[] args) {
        Block first_block = new Block();
        Block previous_block = first_block;
        ArrayList<Block> blockchain = new ArrayList<>();
        Scanner input = new Scanner(System.in);


        int num_of_block_to_add = 20;
        for(int i = 0; i < num_of_block_to_add; i++){
            System.out.println("Message?: ");
            String data = input.nextLine();
            Block block_to_add = previous_block.next_block(data);
            blockchain.add(block_to_add);
            previous_block = block_to_add;
        }

        for(Block block : blockchain){
            System.out.println("Block hash: " + block.hash +
                " | Block P_hash: " + block.prev_hash +  
                " | Block index: " + block.index + 
                " | Block Time Stamp: " + block.timeStamp + 
                " | Block Data: " + block.data);
        }
 
    }
}
