/*
 * This source file was generated by the Gradle 'init' task
 */
package tiny.blockchain;


public class App {
    public static void main(String[] args) {
        Block start = new Block();
        System.out.println(start.hashid+ " " + start.index + " " + start.timeStamp + " " + start.data);
    }
}
